title = "Jonathan Mainguy"
baseURL = "https://jmainguy.com"
theme = "hugo-coder"
languageCode = "en-us"
DefaultContentLanguage = "en"
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
paginate = 10

[params]
  maxSeeAlsoItems = 10
  author = "Jonathan Mainguy"
  description = "Jonathan Mainguy's Blog."
  custom_css = ["custom.css"]
  keywords = "blog,developer,personal"
  info = ["Father", "Husband", "Jesus Freak"]
  avatarURL = "images/avatar.png"
  footerContent = "Take it easy"
  dateFormat = "January 2, 2006"
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = 2010

  colorScheme = "auto"
  hideColorSchemeToggle = false

  [[languages.en.menu.main]]
  name = "Blog"
  weight = 2
  url = "posts/"


  [[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter"
  weight = 3
  url = "https://twitter.com/standouthost"

  [[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/jonathan-mainguy-76174a54/"

  [[params.social]]
  name = "Github"
  icon = "fa fa-github"
  weight = 1
  url = "https://github.com/jmainguy"

  [taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

